# Generated by Django 3.1 on 2020-09-01 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=20)),
                ('book', models.CharField(max_length=65)),
                ('language', models.CharField(choices=[('Tamil', 'Tamil'), ('English', 'English'), ('Sinhala', 'Sinhala')], max_length=10)),
                ('description', models.TextField(max_length=250)),
                ('publisher', models.CharField(max_length=50)),
                ('pub_date', models.DateField()),
                ('pages', models.CharField(max_length=50)),
                ('note', models.CharField(max_length=65)),
                ('edition', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='book_cover')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=65)),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport', models.CharField(max_length=65)),
                ('transport_cost', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('exchange_rates', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('date', models.DateField(max_length=65)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book_API.books')),
            ],
            options={
                'verbose_name_plural': 'Expenses',
            },
        ),
        migrations.AddField(
            model_name='books',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book_API.category'),
        ),
    ]
