# Generated by Django 3.1 on 2020-09-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book_API', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenses',
            options={},
        ),
        migrations.AddField(
            model_name='expenses',
            name='total_book_cost',
            field=models.IntegerField(default=0),
        ),
    ]
