# Generated by Django 3.1 on 2020-09-01 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Book_API', '0002_auto_20200901_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenses',
            options={'verbose_name_plural': 'Expenses'},
        ),
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('total', models.IntegerField(default=0)),
                ('stock', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book_API.books')),
            ],
        ),
    ]
