# Generated by Django 3.1 on 2020-09-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book_API', '0004_auto_20200901_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
