# Generated by Django 3.1 on 2020-09-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book_API', '0005_sales_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
