# Generated by Django 3.1 on 2020-09-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book_API', '0006_auto_20200901_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='banner')),
                ('headline', models.CharField(max_length=65)),
            ],
        ),
    ]
