# Generated by Django 3.1 on 2020-09-02 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book_API', '0007_carousel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name_plural': 'Carousel'},
        ),
    ]
