# Generated by Django 3.1 on 2020-09-02 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Book_API', '0008_auto_20200902_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
