# Generated by Django 3.1 on 2020-09-02 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book_API', '0009_carousel_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='banner',
        ),
    ]
