# Generated by Django 3.1 on 2020-09-02 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book_API', '0010_remove_carousel_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carousel',
        ),
    ]
