# Generated by Django 3.1 on 2020-09-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book_API', '0011_delete_carousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=65)),
                ('banner', models.ImageField(upload_to='web_banner')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
