# Generated by Django 3.1.2 on 2021-01-01 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book_API', '0013_auto_20201231_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='language',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='book',
            field=models.CharField(max_length=65),
        ),
        migrations.AlterField(
            model_name='sales',
            name='book',
            field=models.CharField(max_length=65),
        ),
    ]
