# Generated by Django 3.1.2 on 2021-01-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book_API', '0014_auto_20210101_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
