# Generated by Django 3.1.2 on 2021-01-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book_API', '0016_auto_20210104_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book',
            field=models.CharField(max_length=65, unique=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='isbn',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
