# Generated by Django 3.1.2 on 2021-01-08 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book_API', '0017_auto_20210105_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=65, unique=True),
        ),
    ]
